/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stonybrook_middleboxes_TcpTests */

#ifndef _Included_edu_stonybrook_middleboxes_TcpTests
#define _Included_edu_stonybrook_middleboxes_TcpTests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stonybrook_middleboxes_TcpTests
 * Method:    tcpResetTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_stonybrook_middleboxes_TcpTests_tcpResetTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
